#!/usr/bin/env bash
# Compile shim Java, merge into an APK dex that already contains prior shim classes.
set -euo pipefail
cd "$(dirname "$0")"
SDK="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
API="${ANDROID_API:-35}"
BT="$SDK/build-tools/35.0.0"
PLATFORM="$SDK/platforms/android-$API/android.jar"
[[ -f "$PLATFORM" ]] || { echo "need $PLATFORM" >&2; exit 1; }

BASE_APK="${1:?usage: merge-shim-dex.sh base.apk [out.dex]}"
OUT_DEX="${2:-merged-classes.dex}"

if [[ -z "${JAVA_HOME:-}" ]]; then
  for j in \
    "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home" \
    "/opt/homebrew/opt/openjdk" ; do
    [[ -x "$j/bin/java" ]] && export JAVA_HOME="$j" && break
  done
fi
export PATH="${JAVA_HOME:+$JAVA_HOME/bin}:$PATH"

SMALI_VER=3.0.9
DEXLIB="$SDK/cmdline-tools/latest/lib/external/com/android/tools/smali/smali-dexlib2/3.0.3/smali-dexlib2-3.0.3.jar"
GUAVA="$SDK/cmdline-tools/latest/lib/external/com/google/guava/guava/32.0.1-jre/guava-32.0.1-jre.jar"
[[ -f "$DEXLIB" ]] || DEXLIB="/tmp/smali-dexlib2-${SMALI_VER}.jar"
[[ -f "$GUAVA" ]] || GUAVA="/tmp/guava.jar"
[[ -f "$DEXLIB" ]] || curl -fsSL \
  "https://dl.google.com/dl/android/maven2/com/android/tools/smali/smali-dexlib2/${SMALI_VER}/smali-dexlib2-${SMALI_VER}.jar" \
  -o "$DEXLIB"
[[ -f "$GUAVA" ]] || curl -fsSL \
  "https://repo1.maven.org/maven2/com/google/guava/guava/32.0.1-jre/guava-32.0.1-jre.jar" \
  -o "$GUAVA"
MERGE_CP="$DEXLIB:$GUAVA"

OUT=/tmp/nether-shim-merge-$$
rm -rf "$OUT"
mkdir -p "$OUT/classes" "$OUT/dex"

# Keep the Java side in step with the native build: with NETHER_NO_FSR_FRAMEGEN=1
# libvulkad.so has no FSR path, so the Java must stop writing upscaler=/fsr_* into
# turnip.conf and the game inis, or FSR still reads as "enabled" everywhere.
if [[ "${NETHER_NO_FSR_FRAMEGEN:-0}" == "1" ]]; then SHIM_FSR=false; else SHIM_FSR=true; fi
cat > android/ShimBuildConfig.java <<EOF
package xyz.aethersx2.android.shim;

/** Generated by merge-shim-dex.sh — do not edit. */
final class ShimBuildConfig {
    private ShimBuildConfig() {}
    /** False when libvulkad.so was built with NETHER_NO_FSR_FRAMEGEN=1. */
    static final boolean FSR = $SHIM_FSR;
}
EOF
echo "  ShimBuildConfig.FSR = $SHIM_FSR"

# Generate the variant constant outside the source tree, so sequential builds
# cannot accidentally leave the next variant compiled with the wrong gate.
if [[ "${NETHER_NO_INPROCESS_FRAMEGEN:-0}" == "1" ]]; then SHIM_FRAMEGEN=false; else SHIM_FRAMEGEN=true; fi
cat > "$OUT/FramegenBuild.java" <<EOF
package xyz.aethersx2.android.shim;
final class FramegenBuild { static final boolean AVAILABLE = $SHIM_FRAMEGEN; }
EOF
JAVA_SOURCES=()
for source in android/*.java; do
    [[ "$source" == android/FramegenBuild.java ]] || JAVA_SOURCES+=("$source")
done
javac -source 11 -target 11 -classpath "$PLATFORM" -d "$OUT/classes" "${JAVA_SOURCES[@]}" "$OUT/FramegenBuild.java"
jar cf "$OUT/shim.jar" -C "$OUT/classes" .

"$BT/d8" --release --lib "$PLATFORM" --min-api 29 \
  --output "$OUT/dex/shim.zip" "$OUT/shim.jar"
unzip -qo "$OUT/dex/shim.zip" classes.dex -d "$OUT/dex"

unzip -qo "$BASE_APK" classes.dex -d "$OUT"
javac -source 11 -target 11 -classpath "$MERGE_CP" -d "$OUT/merge" MergeShimDex.java
java -cp "$OUT/merge:$MERGE_CP" MergeShimDex "$OUT/classes.dex" "$OUT/dex/classes.dex" "$OUT/merged.dex"
cp "$OUT/merged.dex" "$OUT_DEX"
rm -rf "$OUT"
echo "Built $OUT_DEX from $BASE_APK"
