package xyz.aethersx2.android.shim;

/** Generated by merge-shim-dex.sh — do not edit. */
final class ShimBuildConfig {
    private ShimBuildConfig() {}
    /** False when libvulkad.so was built with NETHER_NO_FSR_FRAMEGEN=1. */
    static final boolean FSR = false;
}
